#!/bin/bash

ARCH=`uname -m`
KERNEL_VERSION=`uname -r`

DATA_PATH="/home/vyos/zvr/data"
REPOS_PATH="${DATA_PATH}/repos"
HOOKS_PATH="${DATA_PATH}/hooks"
FILE_LISTS_PATH="${DATA_PATH}/file-lists"

CONFIG_PATH="${DATA_PATH}/config"
BOOTUP_CONFIG_FILE="${CONFIG_PATH}/bootup-config.install"
UPDATE_ZVR_FILE="${CONFIG_PATH}/update-zvr.install"
FLAG_X86="X86"
FLAG_ARM="ARM"
FLAG_MIPS="MIPS"
FLAG_GEN="GENERIC"

LOG_FILE="/home/vyos/zvr/zvrconfig.log"
function log_info() {
	echo "$(date -d today '+%Y%m%d %H:%M:%S') - $1"  >> ${LOG_FILE} 2>>${LOG_FILE}
}
